---
- name: Playbook to install python and deploy
  hosts: test_server
  become: true
  gather_facts: false

  tasks:
    - name: Install python
      yum:
        name:python
        state: present

    - name: install docker
      yum:
        name: docker
        state: present

    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
	
    - name: Run Docker container using php-demo-website
      docker_container:
        name: php-demo-website
        image: phpwebsite
        state: started
        recreate: yes
        detach: true
        ports:
          - "32780:8080"