---
- name: Playbook to install python and deploy
  hosts: server
  become: true
  gather_facts: false

  tasks:
    - name: Install python
      yum:
        name: python3
        state: present

    - name: install docker
      yum:
        name: docker-ce
        state: present

    - name: install docker-py python module
      pip:
        name: docker-py
        state: present

    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Run Docker container using php-demo-website
      docker_container:
        name: php-demo-website
        image: phpwebsite
        state: started
        recreate: yes
        detach: true
        ports:
          - "32780:8080"
