---
- name: Playbook to install python and deploy
  hosts: server
  become: true
  gather_facts: false

  tasks:
    - name: Install python
      yum:
        name: python3
        state: present

    - name: install docker
      yum:
        name: docker-ce
        state: present

    - name: install docker-py python module
      pip:
        name: docker-py
        state: present
